eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

server:
  port: 8222

spring:
  application:
    name: Api-GateWay

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Product
          uri: http://localhost:9091/products
          predicates:
            - Path=/products/**

        - id: Supplier
          uri: http://localhost:9092/suppliers
          predicates:
            - Path=/suppliers/**

        - id: Reviews
          uri: http://localhost:9093
          predicates:
            - Path=/reviews/**
      routes[0]:
        filters[0]: AuthenticationFilter
      routes[1]:
        filters[0]: AuthenticationFilter


#  spring:
#    main:
#      web-application-type: reactive